name: hetu
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - bcrypt=3.2.0=py37h5e8e339_1
  - blas=1.0=mkl
  - boto3=1.26.99=pyhd8ed1ab_0
  - botocore=1.29.99=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.14.6=py37hc58025e_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cmake=3.18.2=ha30ef3c_0
  - cryptography=3.4.7=py37h5d9358c_0
  - cub=1.16.0=ha770c72_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - expat=2.4.1=h2531618_2
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - krb5=1.18.2=h173b8e3_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20210216=h27cfd23_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libgomp=9.3.0=h5101ec6_17
  - libprotobuf=3.15.8=h780b84a_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h2531618_0
  - metis=5.1.0=hf484d3e_4
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - mpi=1.0=openmpi
  - nccl=2.8.3.1=hcaf9a05_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - onednn=2.3=omp_hf4ef041_0
  - onnx=1.9.0=py37h284874a_0
  - onnxruntime=1.7.2=py37he8cb6d3_1
  - openmpi=4.0.3=hdf1f1ad_1
  - openssl=1.1.1t=h7f8727e_0
  - pandas=1.2.5=py37h295c915_0
  - paramiko=2.7.2=pyh9f0ad1d_0
  - pip=21.1.3=py37h06a4308_0
  - protobuf=3.15.8=py37hcd2ae1e_0
  - psutil=5.8.0=py37h5e8e339_1
  - pybind11=2.6.2=py37hff7bd54_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pynacl=1.4.0=py37h5e8e339_2
  - pynvml=11.5.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.10=h12debd9_4
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py37h27cfd23_1
  - re2=2021.04.01=h9c3ff4c_0
  - readline=8.1=h27cfd23_0
  - requests=2.28.1=py37h06a4308_0
  - rhash=1.4.1=h3c74f83_1
  - s3transfer=0.6.0=pyhd8ed1ab_0
  - scikit-learn=0.24.2=py37ha9443f7_0
  - scipy=1.6.2=py37had2a1c9_1
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - threadpoolctl=2.2.0=pyhb85f177_0
  - thrust=1.16.0=ha770c72_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.2=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
      - cloudpickle==1.6.0
      - wget==3.2
